import { Project } from "../types/app";
import { bootstrap, css, django, framerMotion, graphql, htmlTech, javascript, materialUI, nextjs, pocketBase, python, react, supabase, tailwind, typescript } from "./technologies";



export default [
    { 
        id: 1,
        name: "Django Academy",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/Academy",
        images: [
            "/assets/projects/django-academy/image-01.png",
            "/assets/projects/django-academy/image-02.png",
            "/assets/projects/django-academy/image-03.png",
            "/assets/projects/django-academy/image-04.png",
            "/assets/projects/django-academy/image-05.png",
            "/assets/projects/django-academy/image-06.png",
            "/assets/projects/django-academy/image-07.png",
            "/assets/projects/django-academy/image-08.png",
            "/assets/projects/django-academy/image-09.png",
            "/assets/projects/django-academy/image-10.png",
            "/assets/projects/django-academy/image-11.png",
            "/assets/projects/django-academy/image-12.png",
            "/assets/projects/django-academy/image-13.png",
            "/assets/projects/django-academy/image-14.png",
        ],
        technologies: [
            python,
            django,
            bootstrap,
            htmlTech,
            css,
            javascript,
        ],
    },
    { 
        id: 2,
        name: "Next Store",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/next-store",
        images: [
            "/assets/projects/next-store/image-01.png",
            "/assets/projects/next-store/image-02.png",
            "/assets/projects/next-store/image-03.png",
            "/assets/projects/next-store/image-04.png",
            "/assets/projects/next-store/image-05.png",
            "/assets/projects/next-store/image-06.png",
            "/assets/projects/next-store/image-07.png",
            "/assets/projects/next-store/image-08.png",
            "/assets/projects/next-store/image-09.png",
        ],
        technologies: [
            nextjs,
            supabase,
            tailwind,
            typescript,
            react,
        ],
    },
    { 
        id: 3,
        name: "Next Blog",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/next-blog",
        images: [
            "/assets/projects/next-blog/image-01.png",
            "/assets/projects/next-blog/image-02.png",
            "/assets/projects/next-blog/image-03.png",
            "/assets/projects/next-blog/image-04.png",
            "/assets/projects/next-blog/image-05.png",
            "/assets/projects/next-blog/image-06.png",
            "/assets/projects/next-blog/image-07.png",
        ],
        technologies: [
            nextjs,
            supabase,
            tailwind,
            typescript,
            react,
        ],
    },
    { 
        id: 4,
        name: "Django Exams App",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/Exams-app",
        images: [
            "/assets/projects/django-exams-app/image-01.png",
            "/assets/projects/django-exams-app/image-02.png",
            "/assets/projects/django-exams-app/image-03.png",
            "/assets/projects/django-exams-app/image-04.png",
            "/assets/projects/django-exams-app/image-05.png",
            "/assets/projects/django-exams-app/image-06.png",
            "/assets/projects/django-exams-app/image-07.png",
            "/assets/projects/django-exams-app/image-08.png",
            "/assets/projects/django-exams-app/image-09.png",
            "/assets/projects/django-exams-app/image-10.png",
            "/assets/projects/django-exams-app/image-11.png",
            "/assets/projects/django-exams-app/image-12.png",
            "/assets/projects/django-exams-app/image-13.png",
            "/assets/projects/django-exams-app/image-14.png",
            "/assets/projects/django-exams-app/image-15.png",
            "/assets/projects/django-exams-app/image-16.png",
            "/assets/projects/django-exams-app/image-17.png",
            "/assets/projects/django-exams-app/image-18.png",
            "/assets/projects/django-exams-app/image-19.png",
            "/assets/projects/django-exams-app/image-20.png",
            "/assets/projects/django-exams-app/image-21.png",
            "/assets/projects/django-exams-app/image-22.png",
            "/assets/projects/django-exams-app/image-23.png",
            "/assets/projects/django-exams-app/image-24.png",
            "/assets/projects/django-exams-app/image-25.png",
            "/assets/projects/django-exams-app/image-26.png",
        ],
        technologies: [
            python,
            django,
            htmlTech,
            css,
            javascript
        ],
    },
    { 
        id: 5,
        name: "React Post App with Pocketbase",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/React_with_Pocketbase",
        images: [
            "/assets/projects/react-post-app-with-pocketbase/image-01.png",
            "/assets/projects/react-post-app-with-pocketbase/image-02.png",
            "/assets/projects/react-post-app-with-pocketbase/image-03.png",
            "/assets/projects/react-post-app-with-pocketbase/image-04.png",
            "/assets/projects/react-post-app-with-pocketbase/image-05.png",
        ],
        technologies: [
            react,
            pocketBase,
            tailwind,
            typescript
        ],
    },
    { 
        id: 6,
        name: "React Family Tree",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/Family_Tree",
        images: [
            "/assets/projects/react-family-tree/image-01.png",
            "/assets/projects/react-family-tree/image-02.png",
            "/assets/projects/react-family-tree/image-03.png",
            "/assets/projects/react-family-tree/image-04.png",
            "/assets/projects/react-family-tree/image-05.png",
            "/assets/projects/react-family-tree/image-06.png",
            "/assets/projects/react-family-tree/image-07.png",
        ],
        technologies: [
            react,
            materialUI,
            graphql,
            javascript,
        ],
    },
    { 
        id: 7,
        name: "Light Social facebook copy",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/Family_Tree",
        images: [
            "/assets/projects/react-light-social/image-01.png",
            "/assets/projects/react-light-social/image-02.png",
            "/assets/projects/react-light-social/image-03.png",
            "/assets/projects/react-light-social/image-04.png",
        ],
        technologies: [
            react,
            tailwind,
            supabase,
            javascript,
        ],
    },
    { 
        id: 8,
        name: "React Portfolio",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque necessitatibus veniam aliquam? Quam asperiores temporibus vero ipsam eligendi accusantium officiis accusamus aut deserunt optio eos, culpa tempora maxime totam animi omnis. Asperiores reiciendis debitis reprehenderit illo non possimus odit in eius, necessitatibus quae ex autem corrupti quisquam fuga quod. Doloremque eligendi facere earum eius consequuntur harum natus dolorem, incidunt est, debitis quo architecto laboriosam vitae reprehenderit id dolores ad consequatur, quas qui beatae. Hic dolores dicta atque commodi autem consectetur odio libero quasi odit doloribus, ratione debitis, totam quam facilis aliquid ab! Inventore recusandae placeat at, omnis iusto ea id?",
        repository: "https://github.com/mohammad-Gazali/mohammed-algazali-portfolio",
        images: [
            "/assets/projects/react-portfolio/image-01.png",
            "/assets/projects/react-portfolio/image-02.png",
            "/assets/projects/react-portfolio/image-03.png",
            "/assets/projects/react-portfolio/image-04.png",
            "/assets/projects/react-portfolio/image-05.png",
            "/assets/projects/react-portfolio/image-06.png",
            "/assets/projects/react-portfolio/image-07.png",
            "/assets/projects/react-portfolio/image-08.png",
        ],
        technologies: [
            react,
            framerMotion,
            tailwind,
            typescript,
        ],
    },
] satisfies Project[];